version: '3'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - frontend
  frontend:
    network_mode: host
    build:
      context: ./frontend

