version: '3'
services:
  backend:
    build:
      context: ./
      dockerfile: app.dockerfile
    ports:
      - "5000:5000"

  enginemain:
    build:
      context: ./
      dockerfile: main.dockerfile
