name: CI (backend)
on:
  workflow_dispatch:
  workflow_call:

defaults:
  run:
    working-directory: ./backend

jobs:
  Unit_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up
        uses: ./.github/workflows/setup-poetry

      - name: Run unit tests
        run: poetry run invoke coverage-xml
      
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          slug: game-ai-platform-team/tira-ai-platform
        with:
          file: ./backend/coverage.xml

  Lint:
    runs-on: ubuntu-latest
    needs: Format

    steps:
      - uses: actions/checkout@v4

      - name: Set up
        uses: ./.github/workflows/setup-poetry

      - name: Run pylint
        run: poetry run pylint src --fail-under=8

  Format:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up
        uses: ./.github/workflows/setup-poetry

      - name: Format code
        run: poetry run invoke format

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions[bot]
          author_email: github-actions[bot]@users.noreply.github.com
          message: Format code
          pull: "--rebase --autostash"
