name: Set up
description: Set up Python and Poetry

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4

    - name: Load cached Poetry installation
      id: cached-poetry
      uses: actions/cache@v3
      with:
        path: ~/.local
        key: poetry-0

    - name: Install Poetry
      if: steps.cached-poetry.outputs.cache-hit != 'true'
      uses: snok/install-poetry@v1

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
        cache: poetry

    - name: Install dependencies
      run: poetry install
      shell: bash
