name: Build

on:
  workflow_run:
    workflows: [CI]
    types:
      - completed
    branches: [dev]
  workflow_dispatch:

concurrency:
  group: build
  cancel-in-progress: true

jobs:
  Build_staging:
    name: "Build (staging)"
    runs-on: ubuntu-latest
    environment: staging
    
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/tira-app:dev
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            MODE=${{ vars.MODE }}

