name: CI

on:
  push:
  pull_request:
    branches: [dev]
  workflow_dispatch:

jobs:
  ci_frontend:
    permissions:
      contents: write

    uses: ./.github/workflows/ci/ci_frontend.yml
  ci_backend:
    permissions:
      contents: write

    uses: ./.github/workflows/ci/ci_backend.yml
