name: CI (backend)
on:
  push:
  pull_request:
<<<<<<< HEAD
    branches: [main, dev]
=======
    branches: [main]
>>>>>>> dev
  workflow_dispatch:

defaults:
  run:
    working-directory: ./backend

jobs:
<<<<<<< HEAD
  Lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
      - name: Analysing the code with pylint
        run: |
          pylint $(git ls-files '*.py')
=======
  Unit_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up
        uses: ./.github/workflows/setup-poetry

      - name: Run unit tests
        run: poetry run coverage run --branch -m pytest src/tests

  Lint:
    runs-on: ubuntu-latest
    needs: Format

    steps:
      - uses: actions/checkout@v4

      - name: Set up
        uses: ./.github/workflows/setup-poetry

      - name: Run pylint
        run: poetry run pylint src --fail-under=8

  Format:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up
        uses: ./.github/workflows/setup-poetry

      - name: Format code
        run: poetry run invoke format

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Format code
>>>>>>> dev
