name: CI (frontend)

on:
  push:
  pull_request:
    branches: [dev]
  workflow_dispatch:

defaults:
  run:
    working-directory: ./frontend

jobs:
  Unit_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: ./.github/workflows/setup-node

      - name: Run unit tests
        run: pnpm run coverage

      - name: Upload coverage report artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-coverage
          path: ./frontend/coverage/coverage-final.json


  Format:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: ./.github/workflows/setup-node

      - name: Format code
        run: pnpm run format

      - name: Fix lint issues
        run: pnpm run lint:fix

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "style: Format code"

  Lint:
    runs-on: ubuntu-latest
    needs: Format

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: ./.github/workflows/setup-node

      - name: Run lint
        run: pnpm run lint
