name: CI (frontend)

on:
  push:
  pull_request:
    branches: [dev]
  workflow_dispatch:
  workflow_call:

defaults:
  run:
    working-directory: ./frontend

jobs:
  Unit_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: ./.github/workflows/setup-node

      - name: Run unit tests
        run: pnpm run coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          slug: game-ai-platform-team/tira-ai-platform
        with:
          files: ./frontend/coverage/coverage-final.json


  Format:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: ./.github/workflows/setup-node

      - name: Format code
        run: pnpm run format

      - name: Fix lint issues
        run: pnpm run lint:fix

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "style: Format code"

  Lint:
    runs-on: ubuntu-latest
    needs: Format

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: ./.github/workflows/setup-node

      - name: Run lint
        run: pnpm run lint
