name: CI/CD

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  ci_frontend:
    name: CI (front-end)
    permissions:
      contents: write

    uses: ./.github/workflows/ci_frontend.yml
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  ci_backend:
    name: CI (back-end)
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      OIDC_CLIENT_ID: ${{ secrets.OIDC_CLIENT_ID }}
      OIDC_CLIENT_SECRET: ${{ secrets.OIDC_CLIENT_SECRET }}
    permissions:
      contents: write

    uses: ./.github/workflows/ci_backend.yml

  e2e_test:
    name: End-to-end test
    secrets:
      OIDC_CLIENT_ID: ${{ secrets.OIDC_CLIENT_ID }}
      OIDC_CLIENT_SECRET: ${{ secrets.OIDC_CLIENT_SECRET }}

    uses: ./.github/workflows/e2e_test.yml

  build:
    name: Build and deploy
    needs: [ci_backend, ci_frontend, e2e_test]
    if: github.event == 'push'

    uses: ./.github/workflows/build.yml
    with:
      environment: staging
    secrets:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
