name: CI/CD

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  ci_frontend:
    name: CI (front-end)
    permissions:
      contents: write

    uses: game-ai-platform-team/workflows/.github/workflows/ci_node.yml@main
    with:
      working-directory: ./frontend
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  ci_backend:
    name: CI (back-end)
    permissions:
      contents: write
      
    uses: game-ai-platform-team/workflows/.github/workflows/ci_python.yml@main
    with:
      working-directory: ./backend
      environment: staging
    secrets: inherit

  ci_game_image:
    name: CI (game-image)
    permissions:
      contents: write
      
    uses: game-ai-platform-team/workflows/.github/workflows/ci_python.yml@main
    with:
      working-directory: ./game-image
      environment: staging
    secrets: inherit

  e2e_test:
    name: End-to-end test

    uses: ./.github/workflows/e2e_test.yml
    with:
      environment: test
      working-directory: ./frontend
      backend-directory: ./backend
    secrets:
      OIDC_CLIENT_ID: ${{ secrets.OIDC_CLIENT_ID }}
      OIDC_CLIENT_SECRET: ${{ secrets.OIDC_CLIENT_SECRET }}
