name: Coverage report
on:
  workflow_run:
    workflows: ["CI (frontend)", "CI (backend)"]
    types:
      - completed
    branches: [dev]
  workflow_dispatch:

jobs:
  Coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Download coverage report artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: "*-coverage"

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          slug: game-ai-platform-team/tira-ai-platform
        with:
          files: ./coverage.xml, ./coverage-final.json
