name: End-to-end testing

on:
  workflow_dispatch:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]

jobs:
  e2e:
    name: End-to-end test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Poetry
        uses: ./.github/workflows/setup-poetry
      - name: Set up Node
        uses: ./.github/workflows/setup-node
      - name: Run e2e tests
        run: bash run_e2e_tests.sh
