name: End-to-end testing
on:
  schedule:
    - cron: 0 */4 * * *
  workflow_dispatch:

defaults:
  run:
    working-directory: ./frontend

jobs:
  e2e_staging:
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - uses: actions/checkout@v4

      - name: Run end-to-end tests
        uses: cypress-io/github-action@v6
