name: End-to-end testing
on:
  schedule:
    - cron: 0 */4 * * *
  workflow_dispatch:

jobs:
  e2e_staging:
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - uses: actions/checkout@v4

      - name: Run end-to-end tests
        uses: cypress-io/github-action@v6
        env:
          CYPRESS_BASE_URL: ${{ secrets.CYPRESS_BASE_URL }}
        with:
          working-directory: frontend
