name: End-to-end testing

on:
  workflow_dispatch:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up
        uses: ./.github/workflows/setup-poetry
      - name: Set up Node
        uses: ./.github/workflows/setup-node
      - name: Do tests
        run: bash run_e2e_tests.sh
