name: End-to-end testing

on:
  workflow_call:

jobs:
  e2e:
    name: End-to-end test
    runs-on: ubuntu-latest
    env:
      NODE_ENV: ${{ vars.NODE_ENV }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Poetry
        uses: ./.github/workflows/setup-poetry

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: latest
          run_install: false

      - name: Run Cypress
        uses: cypress-io/github-action@v6
        with:
          working-directory: ./frontend
          wait-on: "http://localhost:5000"
          wait-on-timeout: 10
          build: pnpm run build
          start: pnpm run server
