name: End-to-end testing

on:
  workflow_call:

jobs:
  e2e:
    name: End-to-end test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Poetry
        uses: ./.github/workflows/setup-poetry

      - name: Set up Node
        uses: ./.github/workflows/setup-node

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/Cypress
          key: cypress-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}
      - run: pnpm install cypress

      - name: Run Cypress
        uses: cypress-io/github-action@v6
        with:
          working-directory: ./frontend
          wait-on: "http://localhost:5000"
          start: |
            cd backend && poetry run invoke start
            cd frontend && pnpm run dev

      - name: Run e2e tests
        run: bash run_e2e_tests.sh
